### ISSUE TITLE
Used featureset of zeromq

### ISSUE THREAD

**Issue by touisteur** [afrl-rq/OpenUxAS#33]
Hi,

I've seen a presentation some time ago about OpenUXAS, and I was (pleasantly) surprised to see it used zeromq. Could you point me to the subset of zmq that you use? What kinds of sockets (rep/req, pub/sub, xpub/xsub, router, etc.) and which APIs?

It might seem a strange question, but I'm looking into building a subset of zmq in a 'safer' dev environment and am looking for some kind of 'completion' / 'usefulness' criterion.

I'd understand if you just said 'try to build it and see for yourself' but I wanted to ask first :-)

Thanks in advance for your kind help.

**Comment by lhumphrey** [comment]
The main developer of the ZMQ framework for UxAS no longer works on the project, but I think this is accurate:
* OpenUxAS uses the ZeroMQ pub/sub pattern for all internal message exchange
* It originally only used the C++ API
* We now have examples that use the Python API, due to collaborators who use Python to interface with OpenUxAS
* We now use the Ada API to enable services to that are written and verified in SPARK/Ada
* OpenUxAS also uses Zyre to set up vehicle-to-vehicle communications. Zyre relies on the ZeroMQ C API, but I'm not sure exactly which zmq socket types it uses.

**Comment by touisteur** [comment]
Thanks for this. Sorry to write after you've closed the ticket but, would there be interest in a full Spark implementation of the necessary zmq bits?

**Comment by lhumphrey** [comment]
I think that sounds very difficult, but yes, there would be interest.
